### ISSUE TITLE
Wrong stats

### ISSUE THREAD

**Issue by mkza** [nicinabox/boxcar#10]
Hi,

The default unRAID screen shows this:

![image](https://f.cloud.github.com/assets/5723509/1365658/ac3dc29e-387e-11e3-9b7c-ef7bfc063a55.png)

boxcar shows this:

![image](https://f.cloud.github.com/assets/5723509/1365659/d0eba354-387e-11e3-8480-389e739a22d4.png)

Same system. 4TB parity. 3 x 3TB data. 9TB usable.

I suspect something wrong with my config rather than boxcar but I think the default menu display is correct rather than boxcar.

Please advise.

**Comment by mkza** [comment]
Meh. Not sure what that was about. It's now working 100% ... displaying the same remaining space as the default menu.

**Comment by nicinabox** [comment]
Strange. Were those screenshots directly after an install?

**Comment by mkza** [comment]
No. They were taken after about half an hour after install and after I was copying data to the array.

I have noticed that the "free amount" that BoxCar is reporting stays stuck on the amount that was free when the unRAID server is started. If I copy say 100Gb to the array then the reported free amount by BoxCar doesn't change.

I'm also noticing now that BoxCar is intermittently not loading when I restart the server. I've been stopping/starting the server a lot over the last few days as I add drives and stop for storms, etc. I've noticed the console on the LCD attached to the server has indicated an error loading BoxCar but probably more likely the Ruby software.

I've just restarted the server to test if BoxCar will load or not and it hasn't.

I have unMenu installed on the server to see what packages are installed.

**Comment by nicinabox** [comment]
Thanks for your feedback!

> I have noticed that the "free amount" that BoxCar is reporting stays stuck on the amount that was free when the unRAID server is started.

Known issue. To be fixed in next release.

> I'm also noticing now that BoxCar is intermittently not loading when I restart the server. 

There are probably some issues around restart persistence. I don't think it's been fully ironed out yet. Part of the issue is gems are not persisted and bundler needs to be rerun. I'm changing how gems are stored to avoid this issue in the next release.

**Comment by mkza** [comment]
Great. Good to know.

Thank you.
