### ISSUE TITLE
Any way you can change the openssl dependency to 0.9.8?

### ISSUE THREAD

**Issue by kylerw** [nicinabox/boxcar#12]
Current version you are using causing issues with some other plugins at the moment.

**Comment by nicinabox** [comment]
Can you give more information about which plugins? I know there are existing plugins that require >=1.0.1

**Comment by kylerw** [comment]
I actually updated the plg of those using 0.9.8 since it appears most are moving to 1.0.1 (albeit slowly) so I don't think you need to consider this any more.
