### ISSUE TITLE
possible incorrect version string

### ISSUE THREAD

**Issue by hlarsen** [nicinabox/boxcar#4]
installed fresh with the bash installer script, then updated and checked version:

Installing...
Clean up...
Finishing...
Updated to 0.2.1!
/usr/lib/ruby/gems/1.9.1/gems/systemu-2.5.2/lib/systemu.rb:31: warning: Insecure world writable dir /bin in PATH, mode 040777
root@archive:~# boxcar version
/usr/lib/ruby/gems/1.9.1/gems/systemu-2.5.2/lib/systemu.rb:31: warning: Insecure world writable dir /bin in PATH, mode 040777
0.2.0
root@archive:~#

**Comment by nicinabox** [comment]
Ahh thanks. I tagged 0.2.1, but didn't update version.rb :(
Bumped to 0.2.2 to fix.
