### ISSUE TITLE
cannot install packages or addons

### ISSUE THREAD

**Issue by hlarsen** [nicinabox/boxcar#5]
failure on package install or addon add:

root@archive:/boot/extra# boxcar package:install nc
/usr/lib/ruby/gems/1.9.1/gems/systemu-2.5.2/lib/systemu.rb:31: warning: Insecure world writable dir /boot/extra/. in PATH, mode 040777
/usr/apps/boxcar/lib/boxcar/helpers.rb:48:in `addons_host': undefined local variable or method`settings' for #Boxcar::Command::Package:0x9006208 (NameError)
        from /usr/apps/boxcar/lib/boxcar/command/package.rb:27:in `install'
        from /usr/apps/boxcar/lib/boxcar/command.rb:100:in`run'
        from /usr/apps/boxcar/lib/boxcar/cli.rb:8:in `start'
        from /usr/apps/boxcar/lib/boxcar.rb:10:in`<top (required)>'
        from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in `require'
        from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in`require'
        from /usr/local/bin/boxcar:9:in `<main>'

**Comment by nicinabox** [comment]
Fixed packages. Command updated to `packages:install` for consistency as well.
